export const MAX_CHARS_PASSWORD = 64;
export const MAX_CHARS_USERNAME = 16;
export const MIN_CHARS_PASSWORD = 4;
export const MIN_CHARS_USERNAME = 4;
export const PASSWORD_RESET_TOKEN_LIFETIME_SECONDS = 3600;
